parameters:
  additionalMSBuildArguments: ''
  displayName: ''
  publishRidAgnosticPackages: false
  skipTests: $(SkipTests)
  targetArchitecture: null
  timeoutInMinutes: 120
  disableVSPublish: false

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.name }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      # Use a hosted pool when possible.
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: NetCorePublic-Pool
        queue: buildpool.windows.10.amd64.vs2017.open
      ${{ if ne(variables['System.TeamProject'], 'public') }}:
        name: NetCoreInternal-Pool
        queue: buildpool.windows.10.amd64.vs2017
    strategy:
      matrix: 
        debug:
          _BuildConfig: Debug
        release:
          _BuildConfig: Release
    workspace:
      clean: all
    variables: 
      CommonMSBuildArgs: >-
        /p:Configuration=$(_BuildConfig)
        /p:OfficialBuildId=$(OfficialBuildId)
        /p:TargetArchitecture=${{ parameters.targetArchitecture }}
        /p:PortableBuild=true
        /p:SkipTests=${{ parameters.skipTests }}
      MsbuildSigningArguments: >-
        /p:CertificateId=400
        /p:DotNetSignType=$(SignType)
      TargetArchitecture: ${{ parameters.targetArchitecture }}
      DisableVSPublish: ${{ parameters.disableVSPublish }}
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        _InternalRuntimeDownloadArgs: ''
      ${{ if ne(variables['System.TeamProject'], 'public') }}:
        _InternalRuntimeDownloadArgs: >-
            /p:DotNetRuntimeSourceFeed=https://dotnetclimsrc.blob.core.windows.net/dotnet
            /p:DotNetRuntimeSourceFeedKey=$(dotnetclimsrc-read-sas-token-base64)

    steps:

    # NuGet's http cache lasts 30 minutes. If we're on a static machine, this may interfere with
    # auto-update PRs by preventing the CI build from fetching the new version. Delete the cache.
    - powershell: Remove-Item -Recurse -ErrorAction Ignore "$env:LocalAppData\NuGet\v3-cache"
      displayName: Clear NuGet http cache (if exists)

    - script: >-
        build.cmd -ci -test
        $(CommonMSBuildArgs)
        $(MsbuildSigningArguments)
        $(_InternalRuntimeDownloadArgs)
      displayName: Build

    - template: steps/upload-job-artifacts.yml
      parameters:
        name: ${{ parameters.name }}
